version: "3.9"
services:
  db:
    image: mysql:8.0.1
    environment:
      MYSQL_ROOT_PASSWORD: ${IMAGE_VIEWER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${IMAGE_VIEWER_MYSQL_DATABASE}
      MYSQL_USER: ${IMAGE_VIEWER_MYSQL_USER}
      MYSQL_PASSWORD: ${IMAGE_VIEWER_MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on: 
        - db
    ports:
      - "${IMAGE_VIEWER_PHPMYADMIN_PORT}:80"

  php:
    build:
        context: ./backend_php
        dockerfile: Dockerfile
    environment:
      IMAGE_VIEWER_PHPMYADMIN_PORT: ${IMAGE_VIEWER_PHPMYADMIN_PORT}
      IMAGE_VIEWER_PHP_PORT: ${IMAGE_VIEWER_PHP_PORT}
      IMAGE_VIEWER_SECRETKEY: ${IMAGE_VIEWER_SECRETKEY}
      IMAGE_VIEWER_MYSQL_HOST: db
      IMAGE_VIEWER_MYSQL_DATABASE: ${IMAGE_VIEWER_MYSQL_DATABASE}
      IMAGE_VIEWER_MYSQL_USER: ${IMAGE_VIEWER_MYSQL_USER}
      IMAGE_VIEWER_MYSQL_PASSWORD: ${IMAGE_VIEWER_MYSQL_PASSWORD}
    volumes:
      - ./backend_php/:/var/www/html
      - /var/www/html/vendor
    depends_on: 
      - db
      - phpmyadmin
    ports:
       - "${IMAGE_VIEWER_PHP_PORT}:80"
  
  go:
    build:
        context: ./backend_golang
        dockerfile: Dockerfile
    environment:
      IMAGE_VIEWER_PHPMYADMIN_PORT: ${IMAGE_VIEWER_PHPMYADMIN_PORT}
      IMAGE_VIEWER_GOLANG_PORT: ${IMAGE_VIEWER_GOLANG_PORT}
      IMAGE_VIEWER_SECRETKEY: ${IMAGE_VIEWER_SECRETKEY}
      IMAGE_VIEWER_MYSQL_HOST: db
      IMAGE_VIEWER_MYSQL_DATABASE: ${IMAGE_VIEWER_MYSQL_DATABASE}
      IMAGE_VIEWER_MYSQL_USER: ${IMAGE_VIEWER_MYSQL_USER}
      IMAGE_VIEWER_MYSQL_PASSWORD: ${IMAGE_VIEWER_MYSQL_PASSWORD}
      IMAGE_VIEWER_MYSQL_PORT: ${IMAGE_VIEWER_MYSQL_PORT}

    volumes:
      - ./backend_golang/:/app
    depends_on: 
      - db
      - phpmyadmin
    ports:
       - "${IMAGE_VIEWER_GOLANG_PORT}:8080"
  
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      IMAGE_VIEWER_BACKEND_HOST: go
      # IMAGE_VIEWER_BACKEND_HOST: php
    ports:
      - ${IMAGE_VIEWER_REACT_PORT}:3000
    depends_on:
      - php
      - go
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    depends_on:
      - react
      - go
      - php
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${IMAGE_VIEWER_NGINX_PORT}:80
