version: "3.9"
services:
  db:
    image: mysql:8.0.1
    environment:
      MYSQL_ROOT_PASSWORD: ${IMAGE_VIEWER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${IMAGE_VIEWER_MYSQL_DATABASE}
      MYSQL_USER: ${IMAGE_VIEWER_MYSQL_USER}
      MYSQL_PASSWORD: ${IMAGE_VIEWER_MYSQL_PASSWORD}
    healthcheck:
      test: "/usr/bin/mysql --user=$$IMAGE_VIEWER_MYSQL_USER --password=$$IMAGE_VIEWER_MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 20s
      retries: 10

  phpmyadmin:
    container_name: ceta_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on: 
        - db
    ports:
      - "${IMAGE_VIEWER_PHPMYADMIN_PORT}:80"

  php:
    build:
        context: ./backend_php
        dockerfile: Dockerfile
    environment:
      IMAGE_VIEWER_PHPMYADMIN_PORT: ${IMAGE_VIEWER_PHPMYADMIN_PORT}
      IMAGE_VIEWER_PHP_PORT: ${IMAGE_VIEWER_PHP_PORT}
      IMAGE_VIEWER_SECRETKEY: ${IMAGE_VIEWER_SECRETKEY}
      IMAGE_VIEWER_MYSQL_HOST: db
      IMAGE_VIEWER_MYSQL_DATABASE: ${IMAGE_VIEWER_MYSQL_DATABASE}
      IMAGE_VIEWER_MYSQL_USER: ${IMAGE_VIEWER_MYSQL_USER}
      IMAGE_VIEWER_MYSQL_PASSWORD: ${IMAGE_VIEWER_MYSQL_PASSWORD}
    volumes:
      - ./backend_php/:/var/www/html
      - /var/www/html/vendor
    depends_on: 
      - db
      - phpmyadmin
    ports:
       - "${IMAGE_VIEWER_PHP_PORT}:8080"
  
  go:
    build:
        context: ./backend_golang
        dockerfile: Dockerfile
    environment:
      IMAGE_VIEWER_PHPMYADMIN_PORT: ${IMAGE_VIEWER_PHPMYADMIN_PORT}
      IMAGE_VIEWER_GOLANG_PORT: ${IMAGE_VIEWER_GOLANG_PORT}
      IMAGE_VIEWER_SECRETKEY: ${IMAGE_VIEWER_SECRETKEY}
      IMAGE_VIEWER_MYSQL_HOST: db
      IMAGE_VIEWER_MYSQL_DATABASE: ${IMAGE_VIEWER_MYSQL_DATABASE}
      IMAGE_VIEWER_MYSQL_USER: ${IMAGE_VIEWER_MYSQL_USER}
      IMAGE_VIEWER_MYSQL_PASSWORD: ${IMAGE_VIEWER_MYSQL_PASSWORD}
      IMAGE_VIEWER_MYSQL_PORT: ${IMAGE_VIEWER_MYSQL_PORT}

    volumes:
      - ./backend_golang/:/app
    depends_on: 
      - db
      - phpmyadmin
    ports:
       - "${IMAGE_VIEWER_GOLANG_PORT}:8080"